version: 2.1
orbs:
  cypress: cypress-io/cypress@1.29.0
workflows:
  build:
    jobs:
      - cypress/run
post-steps:
            - store_test_results:
                path: cypress/results
circleci-cli/install:
      - run: npm test
      - run: npm run manual:tests
      - run: npm run docs